"""Initial database schema

Revision ID: 9575a0a821d4
Revises: 
Create Date: 2025-08-21 22:44:36.231089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9575a0a821d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'API_CLIENT', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False),
    sa.Column('subscription_plan', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE', name='subscriptionplan'), nullable=False),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_last_login_at'), 'users', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_subscription_plan'), 'users', ['subscription_plan'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_APPROVAL', 'REVOKED', name='applicationstatus'), nullable=False),
    sa.Column('tier', sa.Enum('DEVELOPMENT', 'PRODUCTION', 'ENTERPRISE', 'PARTNER', name='applicationtier'), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('callback_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('api_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_by', sa.UUID(), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_api_call_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_approved_at'), 'applications', ['approved_at'], unique=False)
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_deleted_at'), 'applications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_applications_last_api_call_at'), 'applications', ['last_api_call_at'], unique=False)
    op.create_index(op.f('ix_applications_last_used_at'), 'applications', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_suspended_at'), 'applications', ['suspended_at'], unique=False)
    op.create_index(op.f('ix_applications_tier'), 'applications', ['tier'], unique=False)
    op.create_index(op.f('ix_applications_updated_at'), 'applications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.Enum('TIPO1', 'TIPO2', 'TIPO3', name='credentialtype'), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVIEWING', name='processingstatus'), nullable=False),
    sa.Column('extraction_method', sa.Enum('OCR_TESSERACT', 'OCR_GOOGLE_VISION', 'QR_PYZBAR', 'QR_OPENCV', 'QR_EXTRACTOR_PRO', 'AI_OPENAI', 'AI_DEEPSEEK', 'AI_GEMINI', 'AI_CLAUDE', 'HYBRID', name='extractionmethod'), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_duration', sa.Float(), nullable=True),
    sa.Column('personal_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials'))
    )
    op.create_index(op.f('ix_credentials_created_at'), 'credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_credentials_credential_type'), 'credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_credentials_deleted_at'), 'credentials', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_credentials_extraction_method'), 'credentials', ['extraction_method'], unique=False)
    op.create_index(op.f('ix_credentials_file_hash'), 'credentials', ['file_hash'], unique=False)
    op.create_index(op.f('ix_credentials_processing_completed_at'), 'credentials', ['processing_completed_at'], unique=False)
    op.create_index(op.f('ix_credentials_processing_started_at'), 'credentials', ['processing_started_at'], unique=False)
    op.create_index(op.f('ix_credentials_processing_status'), 'credentials', ['processing_status'], unique=False)
    op.create_index(op.f('ix_credentials_updated_at'), 'credentials', ['updated_at'], unique=False)
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.create_table('billing',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('period_type', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'PAY_AS_YOU_GO', name='billingperiod'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('cost_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transactions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('total_credits', sa.Float(), nullable=False),
    sa.Column('total_usage', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('payment_due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_generated_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_sent_at', sa.DateTime(), nullable=True),
    sa.Column('alerts_sent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_billing_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_billing_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing'))
    )
    op.create_index(op.f('ix_billing_application_id'), 'billing', ['application_id'], unique=False)
    op.create_index(op.f('ix_billing_archived_at'), 'billing', ['archived_at'], unique=False)
    op.create_index(op.f('ix_billing_created_at'), 'billing', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_invoice_number'), 'billing', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_billing_is_finalized'), 'billing', ['is_finalized'], unique=False)
    op.create_index(op.f('ix_billing_is_overdue'), 'billing', ['is_overdue'], unique=False)
    op.create_index(op.f('ix_billing_is_paid'), 'billing', ['is_paid'], unique=False)
    op.create_index(op.f('ix_billing_paid_at'), 'billing', ['paid_at'], unique=False)
    op.create_index(op.f('ix_billing_payment_due_date'), 'billing', ['payment_due_date'], unique=False)
    op.create_index(op.f('ix_billing_period_end'), 'billing', ['period_end'], unique=False)
    op.create_index(op.f('ix_billing_period_start'), 'billing', ['period_start'], unique=False)
    op.create_index(op.f('ix_billing_period_type'), 'billing', ['period_type'], unique=False)
    op.create_index(op.f('ix_billing_updated_at'), 'billing', ['updated_at'], unique=False)
    op.create_index(op.f('ix_billing_user_id'), 'billing', ['user_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', 'RETRYING', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='jobpriority'), nullable=False),
    sa.Column('current_stage', sa.Enum('VALIDATION', 'IMAGE_PREPROCESSING', 'OCR_EXTRACTION', 'QR_EXTRACTION', 'AI_PROCESSING', 'DATA_VALIDATION', 'QUALITY_CHECK', 'STORAGE', 'NOTIFICATION', 'COMPLETED', name='processingstage'), nullable=False),
    sa.Column('ai_provider', sa.Enum('OPENAI', 'DEEPSEEK', 'GEMINI', 'CLAUDE', name='aiprovider'), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_at', sa.DateTime(), nullable=True),
    sa.Column('stage_started_at', sa.DateTime(), nullable=True),
    sa.Column('stage_timeout_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('estimated_completion_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('worker_node', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_processing_jobs_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name=op.f('fk_processing_jobs_credential_id_credentials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_processing_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_ai_provider'), 'processing_jobs', ['ai_provider'], unique=False)
    op.create_index(op.f('ix_processing_jobs_application_id'), 'processing_jobs', ['application_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_completed_at'), 'processing_jobs', ['completed_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_created_at'), 'processing_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_credential_id'), 'processing_jobs', ['credential_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_current_stage'), 'processing_jobs', ['current_stage'], unique=False)
    op.create_index(op.f('ix_processing_jobs_deleted_at'), 'processing_jobs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_failed_at'), 'processing_jobs', ['failed_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_priority'), 'processing_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_processing_jobs_started_at'), 'processing_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_timeout_at'), 'processing_jobs', ['timeout_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_updated_at'), 'processing_jobs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_user_id'), 'processing_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_worker_id'), 'processing_jobs', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_worker_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_user_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_updated_at'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_timeout_at'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_started_at'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_priority'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_failed_at'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_deleted_at'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_current_stage'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_credential_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_created_at'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_completed_at'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_application_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_ai_provider'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_billing_user_id'), table_name='billing')
    op.drop_index(op.f('ix_billing_updated_at'), table_name='billing')
    op.drop_index(op.f('ix_billing_period_type'), table_name='billing')
    op.drop_index(op.f('ix_billing_period_start'), table_name='billing')
    op.drop_index(op.f('ix_billing_period_end'), table_name='billing')
    op.drop_index(op.f('ix_billing_payment_due_date'), table_name='billing')
    op.drop_index(op.f('ix_billing_paid_at'), table_name='billing')
    op.drop_index(op.f('ix_billing_is_paid'), table_name='billing')
    op.drop_index(op.f('ix_billing_is_overdue'), table_name='billing')
    op.drop_index(op.f('ix_billing_is_finalized'), table_name='billing')
    op.drop_index(op.f('ix_billing_invoice_number'), table_name='billing')
    op.drop_index(op.f('ix_billing_created_at'), table_name='billing')
    op.drop_index(op.f('ix_billing_archived_at'), table_name='billing')
    op.drop_index(op.f('ix_billing_application_id'), table_name='billing')
    op.drop_table('billing')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_updated_at'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_processing_status'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_processing_started_at'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_processing_completed_at'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_file_hash'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_extraction_method'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_deleted_at'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_type'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_created_at'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_updated_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_tier'), table_name='applications')
    op.drop_index(op.f('ix_applications_suspended_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_last_used_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_last_api_call_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_deleted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_approved_at'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_plan'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_last_login_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###