"""Add processing_time_seconds column to processing_jobs

Revision ID: c3e2ace1f739
Revises: 9575a0a821d4
Create Date: 2025-08-23 19:04:08.624805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c3e2ace1f739'
down_revision = '9575a0a821d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('processing_time_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'processing_time_seconds')
    # ### end Alembic commands ###